import React, { useState } from 'react';
import { aiAPI } from '../../services/api';
import { SymptomCheckResult } from '../../types';
import {
  BrainCircuit, ArrowLeft, Loader2, Sparkles, AlertTriangle,
  Stethoscope, Info, Heart, AlertCircle
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const PRESET_SYMPTOMS = [
  'Fever', 'Cough', 'Shortness of breath', 'Chest Pain', 'Headache',
  'Dizziness', 'Fatigue', 'Nausea', 'Muscle aches', 'Sore Throat'
];

const SymptomChecker = () => {
  const navigate = useNavigate();
  const [selectedSymptoms, setSelectedSymptoms] = useState<string[]>([]);
  const [customSymptom, setCustomSymptom] = useState('');
  const [customList, setCustomList] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<SymptomCheckResult | null>(null);
  const [error, setError] = useState<string>('');

  const handleToggleSymptom = (symptom: string) => {
    if (selectedSymptoms.includes(symptom)) {
      setSelectedSymptoms(selectedSymptoms.filter(s => s !== symptom));
    } else {
      setSelectedSymptoms([...selectedSymptoms, symptom]);
    }
  };

  const handleAddCustom = (e: React.FormEvent) => {
    e.preventDefault();
    if (customSymptom.trim() && !customList.includes(customSymptom.trim())) {
      const val = customSymptom.trim();
      setCustomList([...customList, val]);
      setSelectedSymptoms([...selectedSymptoms, val]);
      setCustomSymptom('');
    }
  };

  const handleAnalyze = async () => {
    if (selectedSymptoms.length === 0) {
      alert('Please select at least one symptom.');
      return;
    }
    setLoading(true);
    setResult(null);
    setError('');

    try {
      const res = await aiAPI.checkSymptoms(selectedSymptoms);
      const data = res.data?.data || res.data;
      
      // Map server properties to camelCase (safely accepting both formats)
      const parsedResult: SymptomCheckResult = {
        possibleConditions: (data.possibleConditions || data.possible_conditions || []).map((c: any) => ({
          condition: c.condition || c.name || '',
          probability: c.probability || 'Medium',
          description: c.description || '',
        })),
        riskLevel: data.riskLevel || data.risk_level || 'low',
        recommendedDepartment: data.recommendedDepartment || data.suggested_department || 'General Medicine',
        suggestedAction: data.suggestedAction || data.recommended_action || 'Consult a doctor.',
        disclaimer: data.disclaimer || 'Assessment generated by AI.',
      };
      setResult(parsedResult);
    } catch (err: any) {
      console.error("Symptom Checker error details:", err);
      const status = err.response?.status;
      const errMsg = (err.response?.data?.error || err.message || '').toLowerCase();
      const isQuota = status === 429 || errMsg.includes('429') || errMsg.includes('quota') || errMsg.includes('limit reached') || errMsg.includes('rate limit');
      
      const userFriendlyMsg = isQuota
        ? "AI service is temporarily unavailable because the daily AI usage limit has been reached. Please try again tomorrow."
        : "Unable to process your request right now. Please try again later.";
      
      setError(userFriendlyMsg);
      setResult(null);
    } finally {
      setLoading(false);
    }
  };

  const getRiskColor = (level: string) => {
    switch (level) {
      case 'critical': return 'bg-red-100 text-red-700 border-red-200';
      case 'high': return 'bg-orange-100 text-orange-700 border-orange-200';
      case 'medium': return 'bg-amber-100 text-amber-700 border-amber-200';
      default: return 'bg-emerald-100 text-emerald-700 border-emerald-200';
    }
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex items-center gap-3">
        <button
          onClick={() => navigate('/ai')}
          className="p-2 bg-white rounded-xl border border-medical-border hover:bg-gray-50 text-medical-muted transition-colors"
        >
          <ArrowLeft size={18} />
        </button>
        <div>
          <h1 className="page-title">AI Symptom Checker</h1>
          <p className="text-medical-muted text-sm mt-1">Analyze symptoms and determine severity risk levels</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Symptoms Selection column */}
        <div className="bg-white rounded-2xl p-6 border border-medical-border shadow-card space-y-6">
          <div className="space-y-2">
            <h3 className="section-title text-sm">Select Your Symptoms</h3>
            <p className="text-xs text-medical-muted">Choose from common symptoms or write custom symptoms below.</p>
          </div>

          {/* Preset list */}
          <div className="flex flex-wrap gap-2">
            {PRESET_SYMPTOMS.map((symptom) => {
              const active = selectedSymptoms.includes(symptom);
              return (
                <button
                  key={symptom}
                  type="button"
                  onClick={() => handleToggleSymptom(symptom)}
                  className={`px-3.5 py-2 rounded-xl text-xs font-semibold border transition-all ${active ? 'bg-teal-600 text-white border-teal-600 shadow-md shadow-teal-600/15' : 'bg-white text-medical-text-secondary border-medical-border hover:bg-gray-50'}`}
                >
                  {symptom}
                </button>
              );
            })}
            {customList.map((symptom) => {
              const active = selectedSymptoms.includes(symptom);
              return (
                <button
                  key={symptom}
                  type="button"
                  onClick={() => handleToggleSymptom(symptom)}
                  className={`px-3.5 py-2 rounded-xl text-xs font-semibold border transition-all ${active ? 'bg-teal-600 text-white border-teal-600 shadow-md shadow-teal-600/15' : 'bg-white text-medical-text-secondary border-medical-border hover:bg-gray-50'}`}
                >
                  {symptom} ✕
                </button>
              );
            })}
          </div>

          {/* Add custom form */}
          <form onSubmit={handleAddCustom} className="flex gap-2">
            <input
              type="text"
              placeholder="Add other symptom (e.g. Back pain)"
              value={customSymptom}
              onChange={(e) => setCustomSymptom(e.target.value)}
              className="w-full px-3 py-2 rounded-xl border border-medical-border text-xs focus:outline-none focus:border-teal-500"
            />
            <button
              type="submit"
              className="px-4 py-2 bg-slate-800 text-white font-bold rounded-xl text-xs shrink-0 hover:bg-slate-900"
            >
              Add
            </button>
          </form>

          {/* Action button */}
          <div className="pt-2">
            <button
              type="button"
              onClick={handleAnalyze}
              disabled={selectedSymptoms.length === 0 || loading}
              className="w-full btn-primary py-3 text-sm flex items-center justify-center gap-1.5 shadow-lg shadow-primary-600/15"
            >
              <Sparkles size={16} /> Evaluate My Symptoms
            </button>
          </div>
        </div>

        {/* Results column */}
        <div className="bg-white rounded-2xl p-6 border border-medical-border shadow-card h-fit min-h-[300px] flex flex-col justify-center">
          {error && (
            <div className="p-4 mb-4 bg-red-50 border border-red-200 rounded-xl text-xs text-red-600 flex items-start gap-2 animate-slide-up">
              <AlertCircle size={16} className="shrink-0 mt-0.5" />
              <div>
                <h4 className="font-bold">AI Service Error</h4>
                <p className="mt-0.5 leading-relaxed">{error}</p>
              </div>
            </div>
          )}

          {loading ? (
            <div className="flex flex-col items-center justify-center py-20 gap-3 text-medical-muted">
              <Loader2 className="animate-spin text-teal-600" size={36} />
              <p className="text-xs font-semibold text-center">Gemini AI is analyzing symptoms profile and compiling diagnosis...</p>
            </div>
          ) : result ? (
            <div className="space-y-6 animate-fade-in text-xs">
              {/* Risk Level Badge */}
              <div className={`p-4 rounded-xl border flex items-start gap-2.5 capitalize ${getRiskColor(result.riskLevel)}`}>
                <AlertTriangle size={18} className="shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-extrabold text-sm">Severity Level: {result.riskLevel}</h4>
                  <p className="text-[11px] opacity-90 mt-0.5">Please review recommendations and department suggestions below.</p>
                </div>
              </div>

              {/* Conditions List */}
              <div className="space-y-3">
                <h4 className="font-bold text-sm text-medical-text-primary flex items-center gap-1">
                  <Stethoscope size={16} className="text-teal-600" /> Possible Diagnoses
                </h4>
                <div className="space-y-3">
                  {result.possibleConditions.map((cond, i) => (
                    <div key={i} className="p-3.5 bg-gray-50 border border-medical-border/60 rounded-xl">
                      <div className="flex justify-between items-center">
                        <span className="font-bold text-medical-text-primary">{cond.condition}</span>
                        <span className="badge badge-info py-0.5 text-[9px]">{cond.probability} Probability</span>
                      </div>
                      <p className="text-medical-muted mt-1.5 leading-relaxed">{cond.description}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Specialist */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="p-4 bg-teal-50/50 border border-teal-100 rounded-xl">
                  <span className="text-[10px] text-teal-700 font-bold block uppercase tracking-wide">Recommended Specialist</span>
                  <span className="text-sm font-bold text-teal-800 block mt-1">{result.recommendedDepartment}</span>
                </div>
                <div className="p-4 bg-primary-50/50 border border-primary-100 rounded-xl">
                  <span className="text-[10px] text-primary-700 font-bold block uppercase tracking-wide">Suggested Actions</span>
                  <span className="text-xs font-semibold text-primary-800 block mt-1">{result.suggestedAction}</span>
                </div>
              </div>

              {/* Disclaimer */}
              <div className="text-[10px] text-medical-muted bg-gray-50 p-3 rounded-lg border border-medical-border leading-relaxed">
                ⚠️ {result.disclaimer}
              </div>
            </div>
          ) : (
            <div className="text-center py-20 text-medical-muted space-y-2">
              <BrainCircuit size={40} className="mx-auto opacity-35 text-teal-600 animate-pulse" />
              <h3 className="font-semibold text-medical-text-primary">Awaiting Symptoms Input</h3>
              <p className="text-xs">Select your current symptoms on the left to begin diagnosis.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default SymptomChecker;
